program: train.py
project: MLOPS_DDPM_G6
metric:
  name: train/loss
  goal: minimize
parameters:
  lr:
    distribution: log_uniform
    min: 1e-5
    max: 1e-2
  lr_warmup_steps:
    values: [5, 10, 20]
  batch_size:
    values: [16, 32, 64]
  epochs:
    values: [5, 10, 20]
  save_model:
    values: [true, false]