program: train.py
method: random
project: MLOPS_DDPM_G6
metric:
  name: train_loss
  goal: minimize
parameters:
  lr:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-2
  batch_size:
    values: [16, 32, 64]
  