name: Code formatting

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  format:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install --upgrade ruff
          pip list
      - name: Verify Ruff Configuration
        run: |
          echo "Using the following pyproject.toml configuration:"
          cat pyproject.toml || echo "No pyproject.toml found"
      - name: Debug Ruff
        run: |
          ruff --version
          ruff show-settings . || echo "No settings found"
          ruff --help
      - name: Ruff check
        run: ruff check .
      - name: Ruff format
        run: ruff format .